version: "3.8"

services:
  mysqldb:
    image: mysql
    restart: unless-stopped
    env_file: .env
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
      - MYSQL_DATABASE=$DB_NAME
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    ports:
      - $DB_PORT:$DB_PORT
    volumes:
      - db:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d

  app:
    depends_on:
      mysqldb :
        condition: service_healthy
    build: ./
    restart: unless-stopped
    env_file: .env
    ports:
      - $HOST_PORT:$HOST_PORT
    environment:
      - DB_HOST=mysqldb
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD
      - DB_NAME=$DB_NAME
      - DB_PORT=$DB_PORT
    stdin_open: true
    tty: true

volumes:
  db:
